using System.ComponentModel;
using GameSpaceManager.Helpers;

namespace GameSpaceManager.Presentation.ManagerPage;

public class FolderItemModel : INotifyPropertyChanged
{
    /// <summary>
    ///     A human-readable size of the folder, e.g. "1.2 GB"
    /// </summary>
    private string _sizeText = string.Empty;

    public string SizeText
    {
        get => _sizeText;
        set
        {
            if (_sizeText != value)
            {
                _sizeText = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(SizeText)));
            }
        }
    }


    /// <summary>
    ///     The name of the folder generated by the last segment of the full path
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    ///     The full path of the folder
    /// </summary>
    public string FullPath { get; set; } = null!;

    /// <summary>
    ///     Only set if the folder is archived
    /// </summary>
    public string? ArchivePath { get; set; }

    /// <summary>
    ///     A flag indicating whether the folder is archived
    /// </summary>
    public bool IsArchived => !string.IsNullOrEmpty(ArchivePath);

    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>
    ///     Gets the size of the folder asynchronously and formats it as a human-readable string
    /// </summary>
    public async Task CalculateSizeAsync()
    {
        var size = await Task.Run(() => GetFolderSize(FullPath));

        if (size == 0 && ArchivePath != null)
            size = await Task.Run(() => GetFolderSize(ArchivePath));

        SizeText = UnitHelpers.FormatDiskSize(size);
    }

    /// <summary>
    ///     Gets the size of the folder in bytes, including all subdirectories and files
    /// </summary>
    /// <param name="folderPath"></param>
    /// <returns></returns>
    private static long GetFolderSize(string folderPath)
    {
        try
        {
            return Directory
                .EnumerateFiles(folderPath, "*", SearchOption.AllDirectories)
                .Sum(f => new FileInfo(f).Length);
        }
        catch
        {
            return 0;
        }
    }
}